name: Bug Report
description: Report a bug in Phloem
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Run `phloem setup cursor`
        2. Open Cursor
        3. ...
    validations:
      required: true

  - type: textarea
    id: doctor
    attributes:
      label: Doctor output
      description: "Paste the output of `phloem doctor`"
      render: shell

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Linux
        - Windows
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Phloem version
      description: "Output of `phloem version`"
    validations:
      required: true

  - type: input
    id: ide
    attributes:
      label: IDE / MCP Client
      description: "e.g., Claude Code, Cursor, VS Code"
