# Homebrew Formula for Phloem
# This is a reference template — the actual formula is auto-generated by
# GoReleaser and pushed to phloemhq/homebrew-tap.
#
# Users install via: brew install phloemhq/tap/phloem

class Phloem < Formula
  desc "Local-first AI memory with causal graphs"
  homepage "https://github.com/CanopyHQ/phloem"
  license "Apache-2.0"

  # GoReleaser fills in version, url, and sha256 automatically.
  # See .goreleaser.yaml brews section.

  def install
    bin.install "phloem"
  end

  test do
    assert_match "protocolVersion", shell_output("echo '{\"jsonrpc\":\"2.0\",\"id\":1,\"method\":\"initialize\",\"params\":{}}' | #{bin}/phloem serve 2>/dev/null | head -1")
  end

  def caveats
    <<~EOS
      Phloem is installed!

      Quick setup:
        phloem setup

      Or configure a specific IDE:
        phloem setup claude-code
        phloem setup cursor
        phloem setup windsurf

      Documentation: https://github.com/CanopyHQ/phloem
    EOS
  end
end
